const jobData = [
  {
    id: 1,
    companyName: "Tech Corp",
    jobTitle: "Junior Developer",
    location: "New York",
    salary: "$50k-$70k",
    tags: "Full-Time",
    category: "Technology",
    logoColor: "bg-blue-500",
    companyLogo: "T"
  },
  {
    id: 2,
    companyName: "Delivery Plus",
    jobTitle: "Delivery Driver",
    location: "Los Angeles",
    salary: "$30k-$40k",
    tags: "Part-Time",
    category: "Delivery & Logistics",
    logoColor: "bg-green-500",
    companyLogo: "D"
  },
  {
    id: 3,
    companyName: "Clean Services",
    jobTitle: "Cleaning Staff",
    location: "Chicago",
    salary: "$25k-$35k",
    tags: "Hourly",
    category: "Cleaning & Maintenance",
    logoColor: "bg-purple-500",
    companyLogo: "C"
  },
  {
    id: 4,
    companyName: "Retail Store",
    jobTitle: "Shop Assistant",
    location: "Boston",
    salary: "$28k-$38k",
    tags: "Full-Time",
    category: "Shop / Store Jobs",
    logoColor: "bg-orange-500",
    companyLogo: "R"
  },
  {
    id: 5,
    companyName: "Café & Kitchen",
    jobTitle: "Barista",
    location: "Seattle",
    salary: "$26k-$36k",
    tags: "Part-Time",
    category: "Restaurant / Café Jobs",
    logoColor: "bg-red-500",
    companyLogo: "K"
  },
  {
    id: 6,
    companyName: "Event Masters",
    jobTitle: "Event Coordinator",
    location: "Miami",
    salary: "$32k-$42k",
    tags: "Seasonal",
    category: "Event & Temporary Work",
    logoColor: "bg-pink-500",
    companyLogo: "E"
  }
];
 export default jobData;



export const INITIALJOBS = [
  {
    id:1,
    jobTitle: "Frontend Developer",
    jobType: "Full-time",
    jobStatus: "active",
    jobShiftType: "Day",
    workingTimeStart: "09:00",
    workingTimeEnd: "18:00",
    salaryMin: "60000",
    salaryMax: "90000",
    salaryType: "Monthly",
    jobSummary: "Develop and maintain user-facing web applications.",
    responsibilities: [
      "Build reusable UI components",
      "Fix UI bugs"
    ],
    requiredSkills: ["React", "JavaScript", "CSS"],
    city: "Bangalore",
    state: "Karnataka",
    country: "India",
    workplaceAddress: "Whitefield, Bangalore",
    applications: 40,
    postedDate: "2015-07-05",
  },
  {
    id:2,
    jobTitle: "Marketing Intern",
    jobType: "Part-time",
    jobStatus: "active",
    jobShiftType: "Day",
    workingTimeStart: "10:00",
    workingTimeEnd: "14:00",
    salaryMin: "8000",
    salaryMax: "12000",
    salaryType: "Monthly",
    jobSummary: "Assist marketing team with campaigns and promotions.",
    responsibilities: [
      "Social media posting",
      "Campaign support"
    ],
    requiredSkills: ["Communication", "Basic Marketing"],
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    workplaceAddress: "Hitech City, Hyderabad",
    applications: 27,
    postedDate: "2023-01-15",
  },
  {
    id:3,
    jobTitle: "Delivery Executive",
    jobType: "Seasonal",
    jobStatus: "active",
    jobShiftType: "Shift",
    workingTimeStart: "16:00",
    workingTimeEnd: "22:00",
    salaryMin: "15000",
    salaryMax: "20000",
    salaryType: "Monthly",
    jobSummary: "Deliver orders to customers on time.",
    responsibilities: [
      "Pick up orders",
      "Ensure timely delivery"
    ],
    requiredSkills: ["Two-Wheeler License", "Time Management"],
    city: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    workplaceAddress: "Anna Nagar, Chennai",
    applications: 22,
    postedDate: "2024-01-15",
  },
  {
    id:4,
    jobTitle: "UX Designer",
    jobType: "Full-time",
    jobStatus: "active",
    jobShiftType: "Day",
    workingTimeStart: "09:30",
    workingTimeEnd: "18:30",
    salaryMin: "70000",
    salaryMax: "100000",
    salaryType: "Monthly",
    jobSummary: "Design intuitive and user-friendly interfaces.",
    responsibilities: [
      "Create wireframes",
      "Conduct usability tests"
    ],
    requiredSkills: ["Figma", "UX Research"],
    city: "Pune",
    state: "Maharashtra",
    country: "India",
    workplaceAddress: "Hinjewadi, Pune",
    applications: 30,
    postedDate: "2023-01-17",
  },
  {
    id:5,
    jobTitle: "Customer Support Executive",
    jobType: "Part-time",
    jobStatus: "active",
    jobShiftType: "Night",
    workingTimeStart: "20:00",
    workingTimeEnd: "02:00",
    salaryMin: "18000",
    salaryMax: "25000",
    salaryType: "Monthly",
    jobSummary: "Handle customer queries via calls and chat.",
    responsibilities: [
      "Answer customer calls",
      "Resolve issues"
    ],
    requiredSkills: ["Communication", "Problem Solving"],
    city: "Coimbatore",
    state: "Tamil Nadu",
    country: "India",
    workplaceAddress: "Gandhipuram, Coimbatore",
    applications: 24,
    postedDate: "2026-01-15",
  }
];

 export const INITIALCANDIDATES=
  [
    {
      id: 1,
      name: 'John Smith',
      email: 'john.smith@email.com',
      profile: 'https://ui-avatars.com/api/?name=John+Smith&background=0D8ABC&color=fff',
      position: 'Senior Software Engineer',
      appliedDate: '2024-12-15',
      status: 'pending',
      phone: '+1 234-567-8900',
      address: '123 Tech Street, San Francisco, CA 94102',
      age: '32',
      language: 'English, Spanish',
      availability: 'Immediate',
      skills: ['React', 'Node.js', 'Python', 'AWS', 'Docker', 'TypeScript'],
      about: 'Passionate software engineer with 8+ years of experience in full-stack development. Specialized in building scalable web applications and leading development teams. Strong problem-solving skills and commitment to writing clean, maintainable code.'
    },
    {
      id: 2,
      name: 'Sarah Johnson',
      email: 'sarah.j@email.com',
      profile: 'https://ui-avatars.com/api/?name=Sarah+Johnson&background=6366F1&color=fff',
      position: 'UX/UI Designer',
      appliedDate: '2024-12-18',
      status: 'pending',
      phone: '+1 234-567-8901',
      address: '456 Design Ave, New York, NY 10001',
      age: '28',
      language: 'English, French',
      availability: '2 weeks notice',
      skills: ['Figma', 'Adobe XD', 'Sketch', 'Prototyping', 'User Research', 'Wireframing'],
      about: 'Creative UX/UI designer with a keen eye for detail and user-centered design principles. Experienced in creating intuitive interfaces that enhance user experience and drive engagement. Portfolio showcases work with Fortune 500 companies.'
    },
    {
      id: 3,
      name: 'Michael Chen',
      email: 'mchen@email.com',
      profile: 'https://ui-avatars.com/api/?name=Michael+Chen&background=EC4899&color=fff',
      position: 'Data Analyst',
      appliedDate: '2024-12-20',
      status: 'pending',
      phone: '+1 234-567-8902',
      address: '789 Analytics Blvd, Austin, TX 78701',
      age: '30',
      language: 'English, Mandarin',
      availability: 'Immediate',
      skills: ['SQL', 'Python', 'Tableau', 'Power BI', 'Excel', 'R'],
      about: 'Data-driven analyst with expertise in transforming complex data into actionable insights. Proven track record of helping organizations make informed business decisions through comprehensive data analysis and visualization.'
    },
    {
      id: 4,
      name: 'Emily Davis',
      email: 'emily.davis@email.com',
      profile: 'https://ui-avatars.com/api/?name=Emily+Davis&background=10B981&color=fff',
      position: 'Marketing Manager',
      appliedDate: '2024-12-22',
      status: 'pending',
      phone: '+1 234-567-8903',
      address: '321 Marketing Lane, Chicago, IL 60601',
      age: '35',
      language: 'English, German',
      availability: '1 month notice',
      skills: ['SEO', 'Content Strategy', 'Analytics', 'Social Media', 'Email Marketing', 'Brand Management'],
      about: 'Results-oriented marketing professional with 10 years of experience driving brand growth and customer engagement. Expertise in digital marketing strategies, campaign management, and cross-functional team leadership.'
    },
    {
      id: 5,
      name: 'David Wilson',
      email: 'dwilson@email.com',
      profile: 'https://ui-avatars.com/api/?name=David+Wilson&background=F59E0B&color=fff',
      position: 'DevOps Engineer',
      appliedDate: '2024-12-25',
      status: 'accepted',
      phone: '+1 234-567-8904',
      address: '654 Cloud Drive, Seattle, WA 98101',
      age: '31',
      language: 'English',
      availability: 'Immediate',
      skills: ['Docker', 'Kubernetes', 'AWS', 'Jenkins', 'Terraform', 'CI/CD'],
      about: 'Experienced DevOps engineer specializing in cloud infrastructure and automation. Strong background in implementing CI/CD pipelines and maintaining highly available systems. Passionate about optimizing workflows and reducing deployment times.'
    },
    {
      id: 6,
      name: 'Lisa Anderson',
      email: 'lisa.a@email.com',
      profile: 'https://ui-avatars.com/api/?name=Lisa+Anderson&background=8B5CF6&color=fff',
      position: 'Product Manager',
      appliedDate: '2024-12-26',
      status: 'rejected',
      phone: '+1 234-567-8905',
      address: '987 Product Way, Boston, MA 02101',
      age: '38',
      language: 'English, Japanese',
      availability: '3 weeks notice',
      skills: ['Agile', 'Scrum', 'Product Strategy', 'Roadmapping', 'User Stories', 'Stakeholder Management'],
      about: 'Strategic product manager with extensive experience launching successful products from concept to market. Skilled at balancing business objectives with user needs and technical constraints. Track record of delivering high-impact features.'
    }
  ]
 